title: navsec
author:
  name: navsec
  email: nav_sec@outlook.com
description: > # this means to ignore newlines until "show_excerpts:"
  Security Research

show_excerpts: false # set to true to show excerpts on the homepage

header_pages:
  - index.md
  - about.md

style: hacker

# Build Settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console

plugins:
 - jekyll-feed
 - jekyll-seo-tag
